name: CI/CD

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    
    - name: Install dependencies
      run: |
        SOPS_VERSION=3.9.4
        curl -LO "https://github.com/mozilla/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64"
        sudo mv sops-v${SOPS_VERSION}.linux.amd64 /usr/local/bin/sops
        sudo chmod +x /usr/local/bin/sops
        sudo apt-get install -y age
        deno task build

    - name: Run tests
      run: |
        chmod +x ./test.sh
        ./test.sh

  release:
    name: Create Release
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    
    - name: Build binary
      run: |
        deno compile --allow-read --allow-write --allow-run --target x86_64-unknown-linux-gnu src/main.ts -o secrets-cli-linux
        deno compile --allow-read --allow-write --allow-run --target x86_64-apple-darwin src/main.ts -o secrets-cli-macos
        deno compile --allow-read --allow-write --allow-run --target x86_64-pc-windows-msvc src/main.ts -o secrets-cli-windows.exe

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          secrets-cli-linux
          secrets-cli-macos
          secrets-cli-windows.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
